name: Metrics
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Cats3153
          committer_token: ${{ github.token }}
          committer_branch: my-branch
          committer_message: Update metrics
          filename: metrics.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          delay: 120
